### ISSUE TITLE
manage the authorization part of swagger definition

### ISSUE THREAD

**Issue by phiz71** [phiz71/vertx-swagger#22]

**Comment by lopesmcc** [comment]
Hello,
I am very interested in this, as I'm starting a project that uses API key authentication and would like to use security definitions on the swagger spec. Because of that, I decided to try to implement it myself.
I experimented on integrating basic and API key based authentication into the router. 
Haven't done it yet for OAuth2. 
Also haven't changed the codegen module yet to configure the auth-providers.

If you want me to, I can prepare a PR with what I've done so far, so that you can review it.
Thanks in advance.

**Comment by phiz71** [comment]
Sure you can prepare a PR ! I have never find time to look at this, so any help is welcome.
Thanks a lot.
(Please PR from a branch and not from your master, I think that may cause troubles with Travis and Sonar addon)
