### ISSUE TITLE
Problems using RX version of SwaggerRouter

### ISSUE THREAD

**Issue by Lakshmihm** [phiz71/vertx-swagger#41]
Hi,

I am using the SwaggerRouter and really like the way it is working.  I am interested in using the RX version of SwaggerRouter io.vertx.rxjava.ext.swagger.router.SwaggerRouter

I could get things working with the core version, but for the RX version I get an empty response. I think I am missing something very basic. Any help in this regard is much appreciated

I am pasting the sample code 

```
vertxFileSystem.readFile("swagger.json", readFile -> {
      if (readFile.succeeded()) {
        Swagger swagger = new SwaggerParser().parse(readFile.result().toString());
        Router swaggerRouter = SwaggerRouter.swaggerRouter(Router.router(vertx), swagger, vertx.eventBus(), new OperationIdServiceIdResolver());
        deployVerticles();
      vertx.createHttpServer().requestHandler(swaggerRouter::accept).rxListen(9004).subscribe(server -> {

          LOGGER.info("API started at: {}", ZonedDateTime.now().format(DateTimeFormatter.BASIC_ISO_DATE.ISO_INSTANT));
          future.complete();
        }, error -> {
          LOGGER.error("Server unable to start: {}", error.getMessage());
          future.fail("Server unable to start");
        });

      } else {
        future.fail(readFile.cause());
      }
    });
```

I have implemented the Verticle by extending the RX version of AbstractVerticle
The server starts up correctly and the request is routed correctly but the response JSON is not rendered

This is my verticle implementation

`vertx.eventBus().<JsonObject> consumer("getProductList").handler(message -> {
			try {
				message.reply(new JsonObject().put("message", "Hello World").encodePrettily());
			} catch (Exception e) {
				message.fail(101,"unexpected Error");
			}
		});`

If you can provide a sample example on how to use the RX version of Swagger Router that would be good. Please feel free to move this if you think it is not an issue. Just need some pointers to see if I am missing anything.

**Comment by philippkumar** [comment]
I think there is a misunderstanding in terms of "RX router".

There is, actually, no RX-variant of the swagger router. What the swagger router does is adding logic on top of a "base router" that you pass during creation, and this passed router can be an RX router if you prefer.

I am not sure that is really required or of much help though. The last commits from @phiz71 (thanks for the awesome work!) regarding RX did not change the router, but instead the code generator, which is IMHO much more helpful.

So, for a swagger spec input file, the code generator can now be configured to generate API service classes with RX methods, so instead of e.g.:
`void addPet(Pet body, Handler<AsyncResult<Void>> handler);`
you will get:
`public Completable addPet(Pet body);`

You can have a look at generated sample code for both variants here:
https://github.com/phiz71/vertx-swagger/tree/master/sample

If you are wondering on how to use the generator, please check:
- https://github.com/phiz71/vertx-swagger/tree/master/modules/vertx-swagger-codegen

You can also see here on how the generator is called from Java:
https://github.com/phiz71/vertx-swagger/blob/master/modules/vertx-swagger-codegen/src/test/java/com/github/phiz71/vertx/swagger/codegen/SampleVertXGeneratorTest.java

You can also do this by using a gradle plugin or similar.

I hope that helped. LEt me know if anything is unclear.

**Comment by phiz71** [comment]
Thanks @philippkumar.
Actually @loeti and @Viiinc commited a Rx version of the Router (#20). (BTW, Thanks to us). But I'm pretty sure, it's not related to this problem...

**Comment by phiz71** [comment]
@Lakshmihm, when you said 

> ...the request is routed correctly but the response JSON is not rendered

Are you sure that your consumer is activated and that `message.reply()` is called ?

**Comment by Lakshmihm** [comment]
Thanks for the response @philippkumar @phiz71 . Really good work. The code generator is really good. But personally I would like to have more control over my code in terms of package structure etc and I prefer to write it myself. I like the idea of documentation driving the code. Ours is a relative small project so we don't need codegen at the moment. I am more interested in using just the SwaggerRouter.

@phiz71 ,
The verticles are deployed. I have put  a logger just before message.reply and it doesn't get printed.
For me it feels like the response is rendered even before message.reply is called. I might be missing something very basic. But difficult to debug. I am still getting used the asynchronous mindset and RX.

**Comment by Lakshmihm** [comment]
@phiz71  just to be clear, when I say empty response it is actually a 400 Bad Request 

 curl -i -X GET "http://localhost:9004/products" -H "accept: application/json"
HTTP/1.1 400 Bad Request
Content-Length: 0

whereas this url works perfectly fine with the core version

**Comment by dfernandezm** [comment]
I was investigating this issue, it happens to me as well. So I found there is a NullPointerException being caught internally when setting up the SwaggerRouter like this:

```
Swagger swagger = new SwaggerParser().parse(readFile.result().toString());

				Router swaggerRouter = SwaggerRouter.swaggerRouter(router, swagger, vertx.eventBus(), new OperationIdServiceIdResolver());

```

That factory method defaults to a `null` `configureMessage`, that gets wrapped in a lambda inside
 `io.vertx.rxjava.ext.swagger.router.SwaggerRouter`:

```
public static Router swaggerRouter(Router baseRouter, Swagger swagger, EventBus eventBus) {
        return swaggerRouter(baseRouter, swagger, eventBus, new DefaultServiceIdResolver(), null);
    }
...
    public static Router swaggerRouter(Router baseRouter, Swagger swagger, EventBus eventBus, ServiceIdResolver serviceIdResolver, Function<RoutingContext, DeliveryOptions> configureMessage) {
        final io.vertx.ext.web.Router baseRouterDelegate = (io.vertx.ext.web.Router) baseRouter.getDelegate();
        final io.vertx.core.eventbus.EventBus eventBusDelegate = (io.vertx.core.eventbus.EventBus) eventBus.getDelegate();

        Function<io.vertx.ext.web.RoutingContext, DeliveryOptions> configureMessageDelegate = rc -> configureMessage.apply(new RoutingContext(rc));

        return new Router(com.github.phiz71.vertx.swagger.router.SwaggerRouter.swaggerRouter(baseRouterDelegate, swagger, eventBusDelegate, serviceIdResolver, configureMessageDelegate));
    }
```

The `configureMessageDelegate` lambda is being created with a null reference to `configureMessage`, which is then actioned at runtime here:

```
 private static void configureRoute(Route route, String serviceId, Operation operation, EventBus eventBus, Function<RoutingContext, DeliveryOptions> configureMessage) {
         ...
        route.handler(context -> {
            try {
                JsonObject message = new JsonObject();
                ...
                // callback to configure message e.g. provide message header values
                DeliveryOptions deliveryOptions = configureMessage != null ? configureMessage.apply(context) : new DeliveryOptions();

            ...
            } catch (RuntimeException e) {
                vertxLogger.debug("sending Bad Request", e);
                badRequestEnd(context.response());
            }

        });

    }
```

The nullcheck is on the lambda (non null) instead of in the value wrapped inside (null). 

As a workaround, SwaggerRouter can be initialized with a default `configureMessage` lambda like this:
```
Swagger swagger = new SwaggerParser().parse(readFile.result().toString());

				Function<RoutingContext, DeliveryOptions> configureMessage = rc -> new DeliveryOptions();

				Router swaggerRouter = SwaggerRouter.swaggerRouter(router, swagger, vertx.eventBus(), new OperationIdServiceIdResolver(), configureMessage);

```
@phiz71 I could provide a PR with a fix in a separate issue if this is agreed to be a bug? Let me know if you agree and if so, what would be the proper fix.

**Comment by phiz71** [comment]
Thanks @dfernandezm  !
Finally I was wrong :) It is related to the Rx version of the SwaggerRouter.
Of course you can provide a PR :) . 

I think the fix should be in `io.vertx.rxjava.ext.swagger.router.SwaggerRouter` : 
`configureMessageDelegate` should be created only if `configureMessage` is not null

Do you agree ?

**Comment by dfernandezm** [comment]
@phiz71 sorry for late response, in training outside office this week. I agree with you, this was my initial idea. I'll on a PR next week. Do you have any specific automated testing requirements?

**Comment by phiz71** [comment]
No specific requirement. Your PR will be built with TravisCI. https://travis-ci.org/phiz71/vertx-swagger
