### ISSUE TITLE
Does the generated code can be changed in a way that works with routingContext apart from eventBus?

### ISSUE THREAD

**Issue by dfernandezm** [phiz71/vertx-swagger#43]
Congratulations in such great project to integrate Swagger in a clean non-invasive way into Vert.x web.

I am a beginner with Vert.x and RxJava, and trying to use your library got generate routing from swagger.json. It is working nice generating code with the `eventBus().consumer` approach, but our team is more familiar with `RoutingContext` and `handler` in the RxJava way, like:

```
router.get("/path").handler(this::handlerName);

....
.flatMap(json -> {
                      
                    }).subscribe(next -> {
                               
                            ,
                            error -> {

                            });
```

Thank you!

**Comment by phiz71** [comment]
Thanks for you support.

I'm not sure I understand your question, sorry.
Do you want the router to call a handler with the routingcontext instead of parsing parameters and sending them on the eventbus ? If so, I don't think it would be possible unless you have the name of your handler written in your swagger definition.

Another solution would be to create new templates which don't use the vertx-swagger-router. IMHO it should generate :
* as many `Handler<>` as operation in the swagger definition
* a router, which would be configured with these `Handler<>`

Originally, my goal was to let the "Router" handle the request / response and to delegate the business part to dedicated Verticles.

But, maybe both implementations could live in the project... just playing with swagger-codegen options.

**Comment by dfernandezm** [comment]
Thank you for prompt response. As you stated:

> Do you want the router to call a handler with the routingcontext instead of parsing parameters and sending them on the eventbus ?

This is exactly what I meant: the handler name to match the `operationId` in the Swagger file and still use all the validation and rules defined there. I think this approach would be somewhat more "direct", but it is just a personal opinion, I am a completely beginner in Vert.x.

Personally, I am not using the codegen part of the library (only first time), my main use case is to define rules (definitions) for requests and responses in Swagger file and get them applied in the code.

But again, this is just my personal view on it. I am absolutely fine using the eventBus, just wondering if you've considered / are possible other approaches.

**Comment by phiz71** [comment]
What I wanted to do was to separate the routing part from the "business" part.
So I've created the SwaggerRouter which aims to configure a Vert.X `Router` using a swagger definition (routing part) while the business part would be managed by verticles which only knows about POJO. I didn't want the request to be sent to verticles nor the response to be computed by verticles.

If I've used handlers instead of parsing the input parameters, that would have meant that SwaggerRouter wouldn't have been as smart as it is,  since the class containing the handlers should have to also manage the `RoutingContext`. You see what I mean ?

But it is not impossible, if you want you can fork the project and try it :) And if you do this, you will have to either drop the codegen part or rewrite it.

**Comment by dfernandezm** [comment]
Understood, I see you point and what you want to achieve. Removing `RoutingContext` management seems like a good win in these kind of applications which become bloated in support code surrounding the business logic. Keep the good work.

**Comment by phiz71** [comment]
Thx ;-)
